<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-13 11:38
=======
# Generated by Django 5.2.4 on 2025-07-17 22:22
>>>>>>> d13de5bf52ee506da75b5cabc482d652413f9b94

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
            ],
        ),
    ]
